### ISSUE TITLE
Invalid URL: https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/source-fonts#2]
I faced with this issue during docker release https://github.com/metanorma/metanorma-docker-private/runs/6173402983?check_suite_focus=true#step:11:43

Should we update URL somewhere in configuration

@alexeymorozov maybe you can help suggest how to fix it?

**Comment by ronaldtse** [comment]
@CAMOBAP somehow I made the release 1.0 into a draft... I've now re-published it. Can you rerun that particular command to see if it works? Sorry!!

**Comment by CAMOBAP** [comment]
@ronaldtse looks like it works, thanks, closing this one

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
